char *myTherapySession[] = { "How can you see into my eyes like open doors?\nLeading you down into my core\nWhere I've become so numb\nWithout a soul\nMy spirit's sleeping somewhere cold\nUntil you find it there and lead it back home\nWake me up inside (save me)\nCall my name and save me from the dark (wake me up)\nBid my blood to run (I can't wake up)\nBefore I come undone (save me)\nSave me from the nothing I've become\nNow that I know what I'm without\nYou can't just leave me\nBreathe into me and make me real\nBring (bring) me (me) to life\nWake me up inside (save me)\nCall my name and save me from the dark (wake me up)\nBid my blood to run (I can't wake up)\nBefore I come undone (save me)\nSave me from the nothing I've become\nBring me to life\nI've been living a lie\nThere's nothing inside\nBring me to life\nFrozen (frozen) inside without your touch\nWithout your love darling\nOnly (only) you are the life among the dead\nAll of this time I can't believe I couldn't see\nKept in the dark but you were there in front of me\nI've been sleeping a thousand years it seems\nGot to open my eyes to everything\nWithout a thought without a voice without a soul\nDon't let me die here\n(There must be something more) bring me to life\nWake me up inside (save me)\nCall my name and save me from the dark (wake me up)\nBid my blood to run (I can't wake up)\nBefore I come undone (save me)\nSave me from the nothing I've become\nBring me to life\nI've been living a lie\nThere's nothing inside\nBring me to life\n",
    
        //Lithium Eva
    "Lithium, don't want to lock me up inside\n"
    "Lithium, don't want to forget how it feels without\n"
    "Lithium, I want to stay in love with my sorrow\n"
    "Don't want to let it lay me down this time\n"
    "Drown my will to fly\n"
    "Here in the darkness I know myself\n"
    "Can't break free until I let it go\n"
    "Let me go\n"
    "Darling, I forgive you after all\n"
    "Anything is better than to be alone\n"
    "And in the end I guess I had to fall\n"
    "Always find my place among the ashes\n"
    "I can't hold on to me\n"
    "Wonder what's wrong with me\n"
    "Lithium, don't want to lock me up inside\n"
    "Lithium, don't want to forget how it feels without\n"
    "Lithium, I want to stay in love with my sorrow\n"
    "Don't want to let it lay me down this time\n"
    "Drown my will to fly\n"
    "Here in the darkness I know myself\n"
    "Can't break free until I let it go\n"
    "Let me go\n"
    "Ooh, ooh, ooh\n"
    "Ooh, ooh, ooh\n"
    "Ooh, ooh, ooh\n"
    "Ooh, ooh, ooh\n"
    "Lithium, don't want to lock me up inside\n"
    "Lithium, don't want to forget how it feels without\n"
    "Lithium, I want to stay in love with my sorrow\n"
    "Stay in love with you\n"
    "Oh\n",

        //My Immortal Eva
    "I'm so tired of being here\n"
    "Suppressed by all my childish fears\n"
    "And if you have to leave\n"
    "I wish that you would just leave\n"
    "'Cause your presence still lingers here\n"
    "And it won't leave me alone\n"
    "These wounds won't seem to heal\n"
    "This pain is just too real\n"
    "There's just too much that time cannot erase\n"
    "When you cried I'd wipe away all of your tears\n"
    "When you'd scream I'd fight away all of your fears\n"
    "And I held your hand through all of these years\n"
    "But you still have\n"
    "All of me\n"
    "You used to captivate me\n"
    "By your resonating light\n"
    "Now I'm bound by the life you left behind\n"
    "Your face it haunts\n"
    "My once pleasant dreams\n"
    "Your voice it chased away\n"
    "All the sanity in me\n"
    "These wounds won't seem to heal\n"
    "This pain is just too real\n"
    "There's just too much that time cannot erase\n"
    "When you cried I'd wipe away all of your tears\n"
    "When you'd scream I'd fight away all of your fears\n"
    "And I held your hand through all of these years\n"
    "But you still have\n"
    "All of me\n"
    "I've tried so hard to tell myself that you're gone\n"
    "But though you're still with me\n"
    "I've been alone all along\n"
    "When you cried I'd wipe away all of your tears\n"
    "When you'd scream I'd fight away all of your fears\n"
    "And I held your hand through all of these years\n"
    "But you still have\n"
    "All of me\n"
    "All of me\n"
    "All of me\n",

    //I hate everything aboout you
    "Every time we lie awake\n"
    "After every hit we take\n"
    "Every feeling that I get\n"
    "But I haven't missed you yet\n"
    "Every roommate kept awake\n"
    "By every sigh and scream we make\n"
    "All the feelings that I get\n"
    "But I still don't miss you yet\n"
    "Only when I stop to think about it\n"
    "I hate everything about you\n"
    "Why do I love you?\n"
    "I hate everything about you\n"
    "Why do I love you?\n"
    "Every time we lie awake\n"
    "After every hit we take\n"
    "Every feeling that I get\n"
    "But I haven't missed you yet\n"
    "Only when I stop to think about it\n"
    "I hate everything about you\n"
    "Why do I love you?\n"
    "I hate everything about you\n"
    "Why do I love you?\n"
    "Only when I stop to think about you\n"
    "I know\n"
    "Only when you stop to think about me\n"
    "Do you know?\n"
    "I hate everything about you\n"
    "Why do I love you?\n"
    "You hate everything about me\n"
    "Why do you love me?\n"
    "I hate\n"
    "You hate\n"
    "I hate\n"
    "You love me\n"
    "I hate everything about you\n"
    "Why do I love you?\n",
            //Pain
    "Pain without love\n"
    "Pain, I can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd rather feel pain than nothing at all\n"
    "You're sick of feeling numb\n"
    "You're not the only one\n"
    "I'll take you by the hand\n"
    "And I'll show you a world that you can understand\n"
    "This life is filled with hurt\n"
    "When happiness doesn't work\n"
    "Trust me and take my hand\n"
    "When the lights go out, you'll understand\n"
    "Pain without love\n"
    "Pain, I can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd rather feel pain than nothing at all\n"
    "Pain without love\n"
    "Pain, I can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd rather feel pain than nothing at all\n"
    "Anger and agony are better than misery\n"
    "Trust me, I've got a plan\n"
    "When the lights go up, you'll understand\n"
    "Pain without love\n"
    "Pain, I can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd rather feel pain than nothing at all\n"
    "Pain, without love\n"
    "Pain, I can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd like to feel pain than nothing\n"
    "Rather feel pain\n"
    "I know, I know, I know, I know, I know\n"
    "That you're wounded\n"
    "You know, you know, you know, you know\n"
    "That I'm here to save you\n"
    "You know, you know, you know, you know\n"
    "I'm always here for you\n"
    "I know, I know, I know, I know\n"
    "That you'll thank me later\n"
    "Pain without love\n"
    "Pain, can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd rather feel pain than nothing at all\n"
    "Pain without love\n"
    "Pain, I can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd rather feel pain than nothing at all\n"
    "Pain without love\n"
    "Pain, I can't get enough\n"
    "Pain, I like it rough\n"
    "'Cause I'd rather feel pain than nothing at all\n"
    "Rather feel pain than nothing at all\n"
    "Rather feel pain\n",

        //Boulevard of Broken Dreams

    "I walk a lonely road\n"
    "The only one that I have ever known\n"
    "Don't know where it goes\n"
    "But it's home to me, and I walk alone\n"
    "I walk this empty street\n"
    "On the Boulevard of Broken Dreams\n"
    "Where the city sleeps\n"
    "And I'm the only one, and I walk alone\n"
    "I walk alone, I walk alone\n"
    "I walk alone, I walk a-\n"
    "My shadow's the only one that walks beside me\n"
    "My shallow heart's the only thing that's beating\n"
    "Sometimes, I wish someone out there will find me\n"
    "'Til then, I walk alone\n"
    "Ah-ah, ah-ah, ah-ah, ah-ah\n"
    "Ah-ah, ah-ah, ah-ah\n"
    "I'm walking down the line\n"
    "That divides me somewhere in my mind\n"
    "On the borderline\n"
    "Of the edge, and where I walk alone\n"
    "Read between the lines\n"
    "What's fucked up, and everything's alright\n"
    "Check my vital signs\n"
    "To know I'm still alive, and I walk alone\n"
    "I walk alone, I walk alone\n"
    "I walk alone, I walk a-\n"
    "My shadow's the only one that walks beside me\n"
    "My shallow heart's the only thing that's beating\n"
    "Sometimes, I wish someone out there will find me\n"
    "'Til then, I walk alone\n"
    "Ah-ah, ah-ah, ah-ah, ah-ah\n"
    "Ah-ah, ah-ah, I walk alone, I walk a-\n"
    "I walk this empty street\n"
    "On the Boulevard of Broken Dreams\n"
    "Where the city sleeps\n"
    "And I'm the only one, and I walk a-\n"
    "My shadow's the only one that walks beside me\n"
    "My shallow heart's the only thing that's beating\n"
    "Sometimes, I wish someone out there will find me\n"
    "'Til then, I walk alone\n",


        //Unforgiven (my hardcoding habbits)
    "New blood joins this earth\n"
    "And quickly he's subdued\n"
    "Through constant pained disgrace\n"
    "The young boy learns their rules\n"
    "With time the child draws in\n"
    "This whipping boy done wrong\n"
    "Deprived of all his thoughts\n"
    "The young man struggles on and on he's known\n"
    "A vow unto his own\n"
    "That never from this day\n"
    "His will they'll take away\n"
    "What I've felt\n"
    "What I've known\n"
    "Never shined through in what I've shown\n"
    "Never be\n"
    "Never see\n"
    "Won't see what might have been\n"
    "What I've felt\n"
    "What I've known\n"
    "Never shined through in what I've shown\n"
    "Never free\n"
    "Never me\n"
    "So I dub thee unforgiven\n"
    "They dedicate their lives\n"
    "To running all of his\n"
    "He tries to please them all\n"
    "This bitter man he is\n"
    "Throughout his life the same\n"
    "He's battled constantly\n"
    "This fight he cannot win\n"
    "A tired man they see no longer cares\n"
    "The old man then prepares\n"
    "To die regretfully\n"
    "That old man here is me\n"
    "What I've felt\n"
    "What I've known\n"
    "Never shined through in what I've shown\n"
    "Never be\n"
    "Never see\n"
    "Won't see what might have been\n"
    "What I've felt\n"
    "What I've known\n"
    "Never shined through in what I've shown\n"
    "Never free\n"
    "Never me\n"
    "So I dub thee unforgiven\n"
    "What I've felt\n"
    "What I've known\n"
    "Never shined through in what I've shown\n"
    "Never be\n"
    "Never see\n"
    "Won't see what might have been\n"
    "What I've felt\n"
    "What I've known\n"
    "Never shined through in what I've shown\n"
    "Never free\n"
    "Never me\n"
    "So I dub thee unforgiven\n"
    "Never free\n"
    "Never me\n"
    "So I dub thee unforgiven\n"
    "You labeled me\n"
    "I'll label you\n"
    "So I dub thee unforgiven\n"
    "Never free\n"
    "Never me\n"
    "So I dub thee unforgiven\n"
    "Never free\n"
    "Never me\n"
    "So I dub thee unforgiven\n",
    
            //Fade to black(my sleep schedule)
    "Life it seems will fade away\n"
    "Drifting further every day\n"
    "Getting lost within myself\n"
    "Nothing matters, no one else\n"
    "I have lost the will to live\n"
    "Simply nothing more to give\n"
    "There is nothing more for me\n"
    "Need the end to set me free\n"
    "Things not what they used to be\n"
    "Missing one inside of me\n"
    "Deathly lost, this can't be real\n"
    "Cannot stand this hell I feel\n"
    "Emptiness is filling me\n"
    "To the point of agony\n"
    "Growing darkness taking dawn\n"
    "I was me, but now he's gone\n"
    "No one but me can save myself, but it's too late\n"
    "Now I can't think, think why I should even try\n"
    "Yesterday seems as though it never existed\n"
    "Death greets me warm, now I will just say goodbye\n"
    "Goodbye\n",

    //How you remind me
    "Never made it as a wise man\n"
    "I couldn't cut it as a poor man stealing\n"
    "Tired of living like a blind man\n"
    "I'm sick of sight without a sense of feeling\n"
    "And this is how you remind me\n"
    "This is how you remind me\n"
    "Of what I really am\n"
    "This is how you remind me\n"
    "Of what I really am\n"
    "It's not like you to say sorry\n"
    "I was waiting on a different story\n"
    "This time I'm mistaken\n"
    "For handing you a heart worth breaking\n"
    "And I've been wrong\n"
    "I've been down\n"
    "To the bottom of every bottle\n"
    "These five words in my head\n"
    "Scream \"Are we having fun yet?\"\n"
    "Yeah, yeah, yeah, no no\n"
    "Yeah, yeah, yeah, no no\n"
    "It's not like you didn't know that\n"
    "I said I love you and I swear I still do\n"
    "And it must have been so bad\n"
    "Cause living with him must have damn near killed you\n"
    "And this is how you remind me\n"
    "Of what I really am\n"
    "This is how you remind me\n"
    "Of what I really am\n"
    "It's not like you to say sorry\n"
    "I was waiting on a different story\n"
    "This time I'm mistaken\n"
    "For handing you a heart worth breaking\n"
    "And I've been wrong\n"
    "I've been down\n"
    "To the bottom of every bottle\n"
    "These five words in my head\n"
    "Scream \"Are we having fun yet?\"\n"
    "Yeah, yeah, yeah, no no\n"
    "Yeah, yeah, yeah, no no\n"
    "Yeah, yeah, yeah, no no\n"
    "Yeah, yeah, yeah, no no\n"
    "Never made it as a wise man\n"
    "I couldn't cut it as a poor man stealing\n"
    "And this is how you remind me\n"
    "This is how you remind me\n"
    "This is how you remind me\n"
    "Of what I really am\n"
    "This is how you remind me\n"
    "Of what I really am\n"
    "It's not like you to say sorry\n"
    "I was waiting on a different story\n"
    "This time I'm mistaken\n"
    "For handing you a heart worth breaking\n"
    "And I've been wrong\n"
    "I've been down\n"
    "To the bottom of every bottle\n"
    "These five words in my head\n"
    "Scream \"Are we having fun yet?\"\n"
    "Yeah, yeah\n"
    "Are we having fun yet?\n"
    "Yeah, yeah\n"
    "Are we having fun yet?\n"
    "Yeah, yeah\n"
    "Are we having fun yet?\n"
    "Yeah, yeah\n"
    "No no\n",

    //Lithium - Nirvana

    
    "I'm so happy 'cause today I found my friends\n"
    "They're in my head\n"
    "I'm so ugly but that's okay 'cause so are you\n"
    "We broke our mirrors\n"
    "Sunday morning is everyday for all I care\n"
    "And I'm not scared\n"
    "Light my candles in a daze 'cause I found God\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "I'm so lonely, that's okay, I shaved my head\n"
    "And I'm not sad\n"
    "And just maybe I'm to blame for all I've heard\n"
    "But I'm not sure\n"
    "I'm so excited, I can't wait to meet you there\n"
    "And I don't care\n"
    "I'm so horny, that's okay, my will is good\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "I like it, I'm not gonna crack\n"
    "I miss you, I'm not gonna crack\n"
    "I love you, I'm not gonna crack\n"
    "I killed you, I'm not gonna crack\n"
    "I like it, I'm not gonna crack\n"
    "I miss you, I'm not gonna crack\n"
    "I love you, I'm not gonna crack\n"
    "I killed you, I'm not gonna crack\n"
    "I'm so happy 'cause today I found my friends\n"
    "They're in my head\n"
    "I'm so ugly, that's okay 'cause so are you\n"
    "We broke our mirrors\n"
    "Sunday morning is everyday for all I care\n"
    "And I'm not scared\n"
    "Light my candles in a daze 'cause I found God\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "Yeah\n"
    "I like it, I'm not gonna crack\n"
    "I miss you, I'm not gonna crack\n"
    "I love you, I'm not gonna crack\n"
    "I killed you, I'm not gonna crack\n"
    "I like it, I'm not gonna crack\n"
    "I miss you, I'm not gonna crack\n"
    "I love you, I'm not gonna crack\n"
    "I killed you, I'm not gonna crack\n"\

        //Fuck me but yes I am this fucking weak

    
    "Time, it needs time\n"
    "To win back your love again\n"
    "I will be there\n"
    "I will be there\n"
    "Love, only love\n"
    "Can bring back your love someday\n"
    "I will be there\n"
    "I will be there\n"
    "Fight, babe, I'll fight\n"
    "To win back your love again\n"
    "I will be there\n"
    "I will be there\n"
    "Love, only love\n"
    "Can bring down the wall someday\n"
    "I will be there\n"
    "I will be there\n"
    "If we'd go again\n"
    "All the way from the start\n"
    "I would try to change\n"
    "Things that killed our love\n"
    "Your pride has built a wall\n"
    "So strong that I can't get through\n"
    "Is there really no chance\n"
    "To start once again?\n"
    "I'm loving you\n"
    "And try, baby, try\n"
    "To trust in my love again\n"
    "I will be there\n"
    "I will be there\n"
    "Love, our love\n"
    "Shouldn't be thrown away\n"
    "I will be there\n"
    "I will be there\n"
    "If we'd go again\n"
    "All the way from the start\n"
    "I would try to change\n"
    "Things that killed our love\n"
    "Your pride has built a wall\n"
    "So strong that I can't get through\n"
    "Is there really no chance\n"
    "To start once again?\n"
    "If we'd go again\n"
    "All the way from the start\n"
    "I would try to change\n"
    "Things that killed our love\n"
    "Yes, I've hurt your pride\n"
    "And I know what you've been through\n"
    "You should give me a chance\n"
    "This can't be the end\n"
    "I'm still loving you\n"
    "I'm still loving you\n"
    "I'm still loving you, I need your love\n"
    "I'm still loving you\n"
    "Still loving you, baby\n"
    "I'm still loving you\n"
    "I need your love\n"
    "I'm still loving you\n"
    "I need your love\n"
    "I need your love\n"
    "I need your love\n"
    "Still loving you\n"

};


//You'll stay as constant Mr.Astley
const char *rickroll = 
    "We're no strangers to love\n"
    "You know the rules and so do I\n"
    "A full commitment's what I'm thinking of\n"
    "You wouldn't get this from any other guy\n"
    "I just wanna tell you how I'm feeling\n"
    "Gotta make you understand\n"
    "Never gonna give you up\n"
    "Never gonna let you down\n"
    "Never gonna run around and desert you\n"
    "Never gonna make you cry\n"
    "Never gonna say goodbye\n"
    "Never gonna tell a lie and hurt you\n"
    "Never gonna give you up\n"
    "Never gonna let you down\n"
    "Never gonna run around and desert you\n"
    "Never gonna make you cry\n"
    "Never gonna say goodbye\n"
    "Never gonna tell a lie and hurt you\n"
    "We've known each other for so long\n"
    "Your heart's been aching but you're too shy to say it\n"
    "Inside we both know what's been going on\n"
    "We know the game and we're gonna play it\n"
    "And if you ask me how I'm feeling\n"
    "Don't tell me you're too blind to see\n"
    "Never gonna give you up\n"
    "Never gonna let you down\n"
    "Never gonna run around and desert you\n"
    "Never gonna make you cry\n"
    "Never gonna say goodbye\n"
    "Never gonna tell a lie and hurt you\n"
    "Never gonna give you up\n"
    "Never gonna let you down\n"
    "Never gonna run around and desert you\n"
    "Never gonna make you cry\n"
    "Never gonna say goodbye\n"
    "Never gonna tell a lie and hurt you\n";



char *ADHDSongs[] = {
        //Angel With A Shotgun
    "I'm an angel with a shotgun\n"
    "Fighting 'til the war's won\n"
    "I don't care if heaven won't take me back\n"
    "I'll throw away my faith, babe, just to keep you safe\n"
    "Don't you know you're everything I have?\n"
    "And I wanna live, not just survive\n"
    "Tonight\n"
    "We'll be the hunters\n"
    "We'll be the hunted\n"
    "We'll be the ones who never back down\n"
    "We'll be the ones who never give up\n"
    "We'll be the ones who never stop\n"
    "We'll be the ones who never drop\n"
    "We'll be the ones who never fall\n"
    "We'll be the ones who stand tall\n"
    "I'm an angel with a shotgun\n"
    "Fighting 'til the war's won\n"
    "I don't care if heaven won't take me back\n"
    "I'll throw away my faith, babe, just to keep you safe\n"
    "Don't you know you're everything I have?\n"
    "And I wanna live, not just survive\n"
    "Tonight\n"
    "We'll be the hunters\n"
    "We'll be the hunted\n"
    "We'll be the ones who never back down\n"
    "We'll be the ones who never give up\n"
    "We'll be the ones who never stop\n"
    "We'll be the ones who never drop\n"
    "We'll be the ones who never fall\n"
    "We'll be the ones who stand tall\n"
    "I'm an angel with a shotgun\n"
    "Fighting 'til the war's won\n"
    "I don't care if heaven won't take me back\n"
    "I'll throw away my faith, babe, just to keep you safe\n"
    "Don't you know you're everything I have?\n"
    "And I wanna live, not just survive\n"
    "Tonight\n",


            //Rockefeller Street
    "Daylight is fading away, night silhouettes in the sky\n"
    "LED lights are flashing on towers\n"
    "It's Manhattan's magical time\n"
    "Ballerinas dancing the Swan Lake\n"
    "On a river made of diamonds and pearls\n"
    "Everything's a little bit weird now\n"
    "Because tonight it is showtime\n"
    "In the middle of the street life\n"
    "All we celebrate are good times\n"
    "Because tonight it is showtime\n"
    "Come and walk with me\n"
    "1273 down the Rockefeller Street\n"
    "Life is marching on, do you feel that?\n"
    "1273 down the Rockefeller Street\n"
    "Everything is more than surreal\n"
    "Alright, let's go, na zdorovje girls\n"
    "Old school Hollywood stars\n"
    "Party cinderellas are here\n"
    "They come for fun and for fear\n"
    "Because tonight it is showtime\n"
    "In the middle of the street life\n"
    "All we celebrate are good times\n"
    "Because tonight it is showtime\n"
    "Come and walk with me\n"
    "1273 down the Rockefeller Street\n"
    "Life is marching on, do you feel that?\n"
    "1273 down the Rockefeller Street\n"
    "Everything is more than surreal\n"
    "So let's go, na zdorovje girls\n"
    "Come and walk with me\n"
    "1273 down the Rockefeller Street\n"
    "Life is marching on, do you feel that?\n"
    "1273 down the Rockefeller Street\n"
    "Everything is more than surreal\n",


    
                //Teeth
    "Some days, you're the only thing I know\n"
    "Only thing that's burning when the nights grow cold\n"
    "Can't look away, can't look away\n"
    "Beg you to stay, beg you to stay, yeah\n"
    "Sometimes, you're a stranger in my bed\n"
    "Don't know if you love me or you want me dead\n"
    "Push me away, push me away\n"
    "Then beg me to stay, beg me to stay, yeah\n"
    "Call me in the morning to apologize\n"
    "Every little lie gives me butterflies\n"
    "Something in the way you're looking through my eyes\n"
    "Don't know if I'm gonna make it out alive\n"
    "Fight so dirty, but your love so sweet\n"
    "Talk so pretty, but your heart got teeth\n"
    "Late night devil, put your hands on me\n"
    "And never, never, never ever let go\n"
    "Fight so dirty, but your love so sweet\n"
    "Talk so pretty, but your heart got teeth\n"
    "Late night devil, put your hands on me\n"
    "And never, never, never ever let go\n"
    "Some days, you're the best thing in my life\n"
    "Sometimes, you're the worst, you stab me in the back\n"
    "Can't look away, can't look away\n"
    "Beg you to stay, beg you to stay, yeah\n"
    "Call me in the morning to apologize\n"
    "Every little lie gives me butterflies\n"
    "Something in the way you're looking through my eyes\n"
    "Don't know if I'm gonna make it out alive\n"
    "Fight so dirty, but your love so sweet\n"
    "Talk so pretty, but your heart got teeth\n"
    "Late night devil, put your hands on me\n"
    "And never, never, never ever let go\n"
    "Fight so dirty, but your love so sweet\n"
    "Talk so pretty, but your heart got teeth\n"
    "Late night devil, put your hands on me\n"
    "And never, never, never ever let go\n"
    "Blood on my shirt, rose in my hand\n"
    "You're looking at me like you don't know who I am\n"
    "Blood on my shirt, heart in my hand\n"
    "Still beating\n"
    "Fight so dirty, but your love so sweet\n"
    "Talk so pretty, but your heart got teeth\n"
    "Late night devil, put your hands on me\n"
    "And never, never, never ever let go\n"
    "Fight so dirty, but your love so sweet\n"
    "Talk so pretty, but your heart got teeth\n"
    "Late night devil, put your hands on me\n"
    "And never, never, never ever let go\n"
    "Teeth\n"
    "Teeth\n"
    "Teeth\n"
    "Never, never, never ever let go\n",

            //Thunder - Updated
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over, we\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n"
    "We down\n\n"
    "We're getting on fire\n"
    "We're rising up higher\n"
    "The bottle is up\n"
    "We're over the top\n"
    "It's time to get wild\n"
    "The time of our life\n"
    "It's happening now\n"
    "We're out of control\n"
    "Together we're rolling\n"
    "Over and over, we\n\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n\n"
    "Na-na-na-na\n"
    "Na-na-na-na\n\n"
    "We gotta rock, rock\n"
    "Party till the last shot\n"
    "Fill that jug and raise your cup up\n"
    "We got chug chug\n"
    "Better take it non stop\n"
    "Hey! Come drink it till the last drop\n\n"
    "So please just let us burning down this place\n"
    "And we will end up in the hall of fame\n"
    "Let's get ready for a drinking game\n"
    "So come and sip it to the last drop\n"
    "Over and over we're\n\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n"
    "Down the river, we're drunk and all of our thumbs went up in the air\n"
    "Sung in the wind and sung to the thunder rolling over and over\n",




            //Take a hint

 
    "Why am I always hit on by the boys I never like?\n"
    "I can always see 'em coming, from the left or from the right\n"
    "I don't want to be a priss, I'm just try'na be polite\n"
    "But it always seems to bite me in the...\n"
    "Ask me for my number, yeah, you put me on the spot\n"
    "You think that we should hook-up, but I think that we should not\n"
    "You had me at hello, then you opened up your mouth\n"
    "And that is when it started going south\n"
    "Oh!\n"
    "Get your hands off my hips, 'fore I'll punch you in the lips\n"
    "Stop your staring at my... Hey!\n"
    "Take a hint, take a hint\n"
    "No you can't buy me a drink, let me tell you what I think\n"
    "I think you could use a mint\n"
    "Take a hint, take a hint\n"
    "T-take a hint, take a hint\n"
    "I hate you like I love you in the same sentence\n"
    "I can't be the one to fill the space in your bed, yeah\n"
    "I guess you think you still got me\n"
    "I could have you if I wanted\n"
    "But sorry, it ain't happening, oh\n"
    "Oh!\n"
    "Get your hands off my hips, 'fore I'll punch you in the lips\n"
    "Stop your staring at my... Hey!\n"
    "Take a hint, take a hint\n"
    "No you can't buy me a drink, let me tell you what I think\n"
    "I think you could use a mint\n"
    "Take a hint, take a hint\n"
    "What about \"no\" don't you get?\n"
    "So go and tell your friends\n"
    "I'm not really interested\n"
    "It's about time that you're leavin'\n"
    "I'm gonna count to three and\n"
    "Open my eyes and\n"
    "You'll be gone\n"
    "One\n"
    "Get your hands off my...\n"
    "Two\n"
    "Or I'll punch you in the...\n"
    "Three\n"
    "Stop your staring at my... Hey!\n"
    "Take a hint, take a hint\n"
    "I am not your missing link\n"
    "Let me tell you what I think\n"
    "I think you could use a mint\n"
    "Take a hint, take a hint\n"
    "Take a hint, take a hint\n"
    "Woah!\n"
    "Get your hands off my hips, 'fore I'll punch you in the lips\n"
    "Stop your staring at my... Hey!\n"
    "Take a hint, take a hint\n"
    "T-take a hint, take a hint\n",

    
        //How to Be a Heartbreaker

    "Rule number one, is that you gotta have fun\n"
    "But baby when you're done, you gotta be the first to run\n"
    "Rule number two, just don't get attached to\n"
    "Somebody you could lose\n"
    "So le-let me tell you\n"
    "This is how to be a heartbreaker\n"
    "Boys they like a little danger\n"
    "We'll get him falling for a stranger\n"
    "A player, singing I lo-lo-lo love you\n"
    "How to be a heartbreaker\n"
    "Boys they like the look of danger\n"
    "We'll get him falling for a stranger\n"
    "A player, singing I lo-lo-lo love you\n"
    "At least I think I do\n"
    "Cause I lo-lo-lo love you\n"
    "Rule number three, wear your heart on your cheek\n"
    "But never on your sleeve, unless you wanna taste defeat\n"
    "Rule number four, gotta be looking pure\n"
    "Kiss him goodbye at the door, and leave him wanting more, more\n"
    "This is how to be a heartbreaker\n"
    "Boys they like a little danger\n"
    "We'll get him falling for a stranger\n"
    "A player, singing I lo-lo-lo love you\n"
    "How to be a heartbreaker\n"
    "Boys they like the look of danger\n"
    "We'll get him falling for a stranger\n"
    "A player, singing I lo-lo-lo love you\n"
    "At least I think I do\n"
    "Cause I lo-lo-lo love you\n"
    "Girls, we do, whatever it will take\n"
    "Cause girls don't want, we don't want our hearts to break in two\n"
    "So it's better to be fake, can't risk losing\n"
    "In love again, babe\n"
    "This is how to be a heartbreaker\n"
    "Boys they like a little danger\n"
    "We'll get him falling for a stranger\n"
    "A player, singing I lo-lo-lo love you\n"
    "How to be a heartbreaker\n"
    "Boys they like the look of danger\n"
    "We'll get him falling for a stranger\n"
    "A player, singing I lo-lo-lo love you\n"
    "Cause I lo-lo-lo love you\n"
    "At least I think I do\n",
    



            //Light it Up
    "Just like the street lights lit this town\n"
    "Like a fire in a blaze, gotta burn it down\n"
    "Can't be afraid to live this out\n"
    "We got this far don't know how\n"
    "I see danger in your eyes\n"
    "They know we'll burn down the night\n"
    "Coming just like the sunrise\n"
    "You know that we gonna light it up\n"
    "Babe, tonight we gonna light it up\n"
    "Babe, tonight we gonna light it up\n"
    "Just like the sunrise, we gonna light it up\n"
    "Now\n"
    "Light it up, light it up\n"
    "We light it, light it up\n"
    "Just like a spark that's breaking out\n"
    "Can't make it stop, can't turn back now\n"
    "We know that's there no room for doubt\n"
    "No we can't turn back now\n"
    "I see danger in your eyes\n"
    "They know we'll burn down the night\n"
    "Coming just like the sunrise\n"
    "You know that we gonna light it up\n"
    "Babe, tonight we gonna light it up\n"
    "Babe, tonight we gonna light it up\n"
    "Just like the sunrise, we gonna light it up\n"
    "Now\n"
    "Light it up, light it up\n"
    "We light it, light it up\n",

            //Pretty Rave Girl 
    "I know this pretty rave girl\n"
    "Always think about her\n"
    "And when she says hi to me\n"
    "Butterflies go right through me\n"
    "And when I see her dancing\n"
    "Wanna take a chance in\n"
    "Getting a little closer\n"
    "And maybe get to know her\n"
    "Pretty rave girl\n"
    "I know this pretty rave girl\n"
    "Always think about her\n"
    "And when she says hi to me\n"
    "Butterflies go right through me\n"
    "And when I see her dancing\n"
    "Wanna take a chance in\n"
    "Getting a little closer\n"
    "And maybe get to know her\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "I know this pretty rave girl\n"
    "Always think about her\n"
    "And when she says hi to me\n"
    "Butterflies go right through me\n"
    "And when I see her dancing\n"
    "Wanna take a chance in\n"
    "Getting a little closer\n"
    "And maybe get to know her\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n"
    "Pretty rave girl\n",

        //All I Ever Wanted

    "All I ever wanted was to see you smiling\n"
    "I know that I love you, oh baby why don't you see\n"
    "All I ever wanted was to see you smiling\n"
    "All I ever wanted was to make you mine\n"
    "I know that I love you, oh baby why don't you see\n"
    "That all I ever wanted was you and me\n"
    "All I ever wanted was to see you smiling\n"
    "All I ever wanted was to make you mine\n"
    "I know that I love you, oh baby why don't you see\n"
    "That all I ever wanted was you and me\n"
    "Drop the bass\n"
    "I'm so alone\n"
    "Here on my own\n"
    "And I'm waiting for you to come\n"
    "I want to be a part of you\n"
    "Think of all the things we could do\n"
    "And everyday\n"
    "You're in my head\n"
    "I want to have you in my bed\n"
    "You are the one\n"
    "You're in my eyes\n"
    "All I ever wanted in my life\n"
    "All I ever wanted was to see you smiling\n"
    "All I ever wanted was to make you mine\n"
    "I know that I love you, oh baby why don't you see\n"
    "That all I ever wanted was you and me\n"
    "All I ever wanted was to see you smiling\n"
    "All I ever wanted was to make you mine\n"
    "I know that I love you oh baby why don't you see\n"
    "That all I ever wanted was you and me\n"
    "Are you ready?\n"
    "All I ever wanted was to see you smiling\n"
    "All I ever wanted was to make you mine\n"
    "I know that I love you, oh baby why don't you see\n"
    "That all I ever wanted was you and me\n"
    "All I ever wanted\n",

        //Angel of Darkness

    "Angel of Darkness\n"
    "Angel of Darkness\n"
    "The world is in your hand\n"
    "But I will fight until the end\n"
    "Angel of Darkness\n"
    "Angel of Darkness\n"
    "Don't follow your command\n"
    "But I will fight and I will stand\n"
    "When darkness falls pain is all\n"
    "The Angel of Darkness\n"
    "Will leave behind and I will fight\n"
    "The love is lost\n"
    "Beauty and light\n"
    "Have vanished from garden of delight\n"
    "The dreams are gone\n"
    "Midnight has come\n"
    "The darkness is our new kingdom\n"
    "Angel of Darkness\n"
    "Angel of Darkness\n"
    "The world is in your hand\n"
    "But I will fight until the end\n"
    "Angel of Darkness\n"
    "Angel of Darkness\n"
    "Don't follow your command\n"
    "But I will fight and I will stand\n"
    "Hunt goes on deep in the night\n"
    "Time to pray down on your knees\n"
    "You can't hide from me\n"
    "Etern the light\n"
    "Until my last breath I will fight\n"
    "(I will fight, I will fight, I will fight, I will fight)\n"
    "Now realize\n"
    "The stars they die\n"
    "Darkness has fallen in paradise\n"
    "But we'll be strong\n"
    "And we will fight\n"
    "Against the creatures of the night\n"
    "Angel of Darkness\n"
    "Angel of Darkness\n"
    "The world is in your hand\n"
    "But I will fight until the end\n"
    "Angel of Darkness\n"
    "Angel of Darkness\n"
    "Don't follow your command\n"
    "But I will fight and I will stand\n",


            //Pretty Little Psycho

    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Walkin', talkin' like you know\n"
    "I want your pretty little psycho\n"
    "(Pretty little psycho)\n\n"

    "I'm ready to go, I'm taking chances\n"
    "Sippin' lust from champagne glasses\n"
    "Gotta have you, I'm movin' closer\n"
    "I won't take no for an answer\n"
    "You're lookin' crazy, you're lookin' wrong\n"
    "It looks like we're gonna get along\n"
    "And once I've got you, it's a fact\n"
    "Baby, there's no turning back\n\n"

    "Make me, make me impressed\n"
    "Make me, make me obsessed\n\n"

    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Walkin', talkin' like you know\n"
    "I want your pretty little psycho\n"
    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Baby strike a pose\n"
    "I want your pretty little psycho\n\n"

    "Pretty little, pretty little, pretty little psycho\n"
    "Pretty little, pretty little\n"
    "Pretty little psycho\n"
    "Pretty little, pretty little, pretty little psycho\n"
    "Pretty little, pretty little\n"
    "Pretty little psycho\n\n"

    "Black lipstick just like a cat\n"
    "Have you purrin' on your back\n"
    "Tip the glass, now light it up\n"
    "Rebel, rebel can't get enough\n"
    "You're lookin' crazy, you're lookin' wrong\n"
    "We look like we belong\n"
    "And once I've got you, it's a fact\n"
    "Baby, there's no turning back\n\n"

    "Make me, make me impressed\n"
    "Make me, make me obsessed\n\n"

    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Walkin', talkin' like you know\n"
    "I want your pretty little psycho\n"
    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Baby strike a pose\n"
    "I want your pretty little psycho\n\n"

    "Pretty little, pretty little, pretty little psycho\n"
    "Pretty little, pretty little\n"
    "Pretty little psycho\n"
    "Pretty little, pretty little, pretty little psycho\n"
    "Pretty little, pretty little\n"
    "Pretty little psycho\n\n"

    "There's somethin' about you driving me mad\n"
    "There's somethin' about you I've got to have\n"
    "There's somethin' about you\n"
    "There's somethin' about you\n"
    "There's somethin' about you driving me mad\n"
    "There's somethin' about you I've got to have\n"
    "There's somethin' about you\n"
    "There's somethin' about you\n\n"

    "Oh, oh, oh  \n"
    "Oh, here we go                 \n"
    "Walkin', talkin' like you know\n"
    "I want your pretty little psycho\n"
    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Baby strike a pose\n"
    "I want your pretty little psycho\n\n"

    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Walkin', talkin' like you know\n"
    "I want your pretty little psycho\n"
    "Oh, oh, oh\n"
    "Oh, here we go\n"
    "Baby strike a pose\n"
    "I want your pretty little psycho\n\n"

    "Pretty little, pretty little, pretty little psycho\n"
    "Pretty little, pretty little\n"
    "Pretty little psycho\n"
    "Pretty little, pretty little, pretty little psycho\n"
    "Pretty little, pretty little\n"
    "Pretty little psycho\n"
    
};


char *NWOBHSongs[] = {

        //Ace of Spades 

    "If you like to gamble\n"
    "I tell you, I'm your man\n"
    "You win some, lose some\n"
    "It's all the same to me\n"
    "The pleasure is to play\n"
    "Makes no difference what you say\n"
    "I don't share your greed\n"
    "The only card I need\n"
    "Is the Ace of Spades\n"
    "The Ace of Spades\n\n"
    "Playing for the high one\n"
    "Dancing with the devil\n"
    "Going with the flow\n"
    "It's all a game to me\n"
    "Seven or eleven\n"
    "Snake eyes watching you\n"
    "Double up or quit\n"
    "Double stake or split\n"
    "The Ace of Spades\n"
    "The Ace of Spades\n\n"
    "You know I'm born to lose\n"
    "And gambling's for fools\n"
    "But that's the way I like it, baby\n"
    "I don't want to live forever\n"
    "And don't forget the joker\n\n"
    "Pushing up the ante\n"
    "I know you got to see me\n"
    "Read 'em and weep\n"
    "The dead man's hand again\n"
    "I see it in your eyes\n"
    "Take one look and die\n"
    "The only thing you see\n"
    "You know it's gonna be\n"
    "The Ace of Spades\n"
    "The Ace of Spades, uh\n",


        //Overkill

    "Only way to feel the noise is when it's good and loud\n"
    "So good I can't believe it, screaming with the crowd\n"
    "Don't sweat it, we'll get it back to you\n"
    "Don't sweat it, we'll get it back to you\n"
    "Overkill, overkill, overkill\n\n"
    "On your feet you feel the beat, it goes straight to your spine\n"
    "Shake your head you must be dead if it don't make you fly\n"
    "Don't sweat it, we'll get it back to you\n"
    "Don't sweat it, we'll get it back to you\n"
    "Overkill, overkill, overkill\n\n"
    "Know your body's made to move, ya feel it in your guts\n"
    "Rock 'n' roll ain't worth the name if it don't make ya strut\n"
    "Don't sweat it, we'll get it back to you\n"
    "Don't sweat it, we'll get it back to you\n"
    "Overkill, overkill, overkill\n", 


        //Too late Too Late

    "I see that nothing's changed\n"
    "Insist on playing games\n"
    "Some waste of time you are\n"
    "And you're so popular\n"
    "Well, this is it, you bitch\n"
    "I got to make a switch\n"
    "You find some other John\n"
    "I know what's going on\n\n"
    "Good move\n"
    "What do I have to lose?\n"
    "Stalemate\n"
    "Too late, too late\n\n"
    "I thought you were for real\n"
    "Just one more rip-off deal\n"
    "Don't give me all that crap\n"
    "I just escaped your trap\n"
    "You think you see the joke\n"
    "But you're just chasing smoke\n"
    "'Cause now the thrill is gone\n"
    "I know what's going on\n\n"
    "Good move\n"
    "What do I have to lose?\n"
    "Stalemate\n"
    "Too late, too late\n\n"
    "Misunderstanding me\n"
    "The way you felt so free\n"
    "I'm gonna jump the gun\n"
    "I'm gonna cut and run\n"
    "Your credibility\n"
    "Don't cut no ice with me\n"
    "You're just a feeble con\n"
    "I know what's going on\n\n"
    "Good move\n"
    "What do I have to lose?\n"
    "Stalemate\n"
    "Too late, too late\n"
    "Too late, too late\n",

        //Am I Evil? (spoiler alert nope I am autistic af)
    "My mother was a witch\nShe was burned alive\n"
    "Thankless little bitch\nFor the tears I cried\n"
    "Take her down now\nDon't want to see her face\n"
    "Blistered and burned\nCan't hide my disgrace\n\n"
    "Twenty-seven, everyone was nice\n"
    "Got to see them\nMake them pay the price\n"
    "See their bodies out on the ice\n"
    "Take my time\n\n"
    "Am I evil?\nYes, I am\n"
    "Am I evil?\nI am, man\nYes, I am\n\n"
    "As I watched my mother die\nI lost my head\n"
    "Revenge now I sought to break with my bread\n"
    "Taking no chances\nYou come with me\n"
    "I'll split you to the bone\nHelp set you free\n\n"
    "Twenty-seven\nEveryone was nice\n"
    "Got to see them\nMake them pay the price\n"
    "See their bodies out on the ice\n"
    "Take my time\n\n"
    "Am I evil?\nYes, I am\n"
    "Am I evil?\nI am, man, yes, I am\n\n"
    "Ohoh!\n\n"
    "On with the action now\nI'll strip your pride\n"
    "I'll spread your blood around\nI'll see you ride\n"
    "Your face is scarred with steel\nWounds deep and neat\n"
    "Like a double dozen before you\nSmells so sweet\n\n"
    "Am I evil?\nYes, I am\n"
    "Am I evil?\nI am, man\n\n"
    "My soul is longing before\nAwait my hell\n"
    "Sent to avenge my mother\nSleep myself\n"
    "My face is long forgotten\nMy face not my own\n"
    "Sweet and timely whore\nTake me home\n\n"
    "Am I evil?\nYes I am\n"
    "Am I evil?\nI am, man, yes, I am\n"
    "Oh\n\n"
    "On with the action now, I'll strip your pride\n"
    "I'll spread your blood around, I'll see you ride\n"
    "Your face is scarred with steel, your spirits dance\n"
    "Like a double dozen before you, no romance\n\n"
    "Am I evil? Yes, I am\n"
    "Am I evil? I am, man\n"
    "Am I evil? Yes, I am\n"
    "Am I evil? I am, man, yes, I am\n",

                //In the Heat of The Night 
    "Steely eyes of a silvery people\n"
    "Walk behind me, with evil intent\n"
    "Up to the tower, I stand alone\n"
    "Stripped of rank before them I'm sent\n\n"
    "What befalls us in the heat of the night?\n"
    "What befalls us in the heat of the night?\n\n"
    "Before long, behind adamantine doors\n"
    "I taste of the wine of their joy\n"
    "Through delirium of a tortured mind\n"
    "Her face gave me strength to this day\n\n"
    "What befalls us in the heat of the night?\n"
    "What befalls us in the heat of the night?\n"
    "In the heat of the night\n\n"
    "But love deceived me, and in my despair\n"
    "I recalled the ring once again\n"
    "Born of Sorrow my cunning revives me\n"
    "And I took them with me enchained\n\n"
    "What befalls us in the heat of the night?\n"
    "What befalls us in the heat of the night?\n"
    "In the heat of the night\n",

        //Denim&Leather

    "Where were you in '79 when the dam began to burst\n"
    "Did you check us out down at the local show\n"
    "Were you wearing denim, wearing leather\n"
    "Did you run down to the front\n"
    "Did you queue for your ticket through the ice and snow\n\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n\n"
    "Did you read the music paper from the back and to the front\n"
    "Did you find out where to see your favorite band\n"
    "Did you listen to the radio every Friday night\n"
    "Did hang around your local record store\n\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n\n"
    "Do you dream of playing guitar or smashing up the drums\n"
    "Maybe you can learn to play the bass\n"
    "You can always be a singer like me and front the band\n"
    "When on the stage we wait at your command\n\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n\n"
    "It was you - that set the spirit free\n"
    "It was you - that put us here today\n"
    "It was you - that filled the concert halls\n"
    "It was you - that set the spirit free\n\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n"
    "Denim and Leather\n"
    "Brought us all together\n"
    "It was you that set the spirit free\n",
            
    
                //Crusader
    "Crusader, crusader, please take me with you\n"
    "The battle lies far to the east\n"
    "Crusader, crusader, don't leave me alone\n"
    "I want to ride out on your quest\n"
    "I'm waiting, I'm waiting, to stand by your side\n"
    "To fight with you over the sea\n"
    "They're calling, they're calling, I have to be there\n"
    "The holy land has to be free\n\n"
    "Fight the good fight, believe what is right\n"
    "Crusader, the Lord of the Realm\n"
    "Fight the good fight with all your might\n"
    "Crusader, the Lord of the Realm\n\n"
    "We're marching, we're marching, to a land far from home\n"
    "No one can say who'll return\n"
    "For Christendom's sake, we'll take our revenge\n"
    "On the pagans from out of the east\n"
    "We Christians are coming, with swords held on high\n"
    "United by faith and the cause\n"
    "The Saracen heathen will soon taste our steel\n"
    "Our standards will rise 'cross the land\n\n"
    "Fight the good fight, believe what is right\n"
    "Crusader, the Lord of the Realm\n"
    "Fight the good fight with all your might\n"
    "Crusader, the Lord of the Realm\n\n"
    "To battle, to battle, the Saracen hordes\n"
    "We follow the warrior king\n"
    "Onward, ride onward, into the fight\n"
    "We carry the sign of the cross\n"
    "Warlords of England, Knights of the Realm\n"
    "Spilling their blood in the sand\n"
    "Crusader, crusader, the legend is born\n"
    "The future will honour your deeds\n\n"
    "Fight the good fight, believe what is right\n"
    "Crusader, the Lord of the Realm\n"
    "Fight the good fight with all your might\n"
    "Crusader, the Lord of the Realm\n",
            
    
    
            //Fire in The SKYYYY
    "There's a fire in the sky\n"
    "There's a feeling in the air\n"
    "When the ground starts to tremble\n"
    "The first attack is here\n\n"
    "You won't stand a chance\n"
    "When the missiles start to fly\n"
    "They never tell the people\n"
    "'Til the holocaust is here\n\n"
    "When the fire's in the sky\n"
    "You'll be running for your lives\n"
    "When the fire's in the sky\n"
    "Prepare yourselves to die\n\n"
    "Where, where are the shelters?\n"
    "They said they would be there\n"
    "You'll need, need some protection\n"
    "From the radiation flare\n\n"
    "Don't, don't start a panic\n"
    "It won't do you no good\n"
    "You'll just have to wait\n"
    "For the end of all mankind\n\n"
    "If you're near the point of impact\n"
    "There's nowhere you can run\n"
    "If the heatwave don't get you\n"
    "The shockwave surely will\n\n"
    "There won't be no more heroes\n"
    "There's no one left to fight\n"
    "It's the end of our planet\n"
    "We'd commit eternal sight\n\n"
    "When the fire's in the sky\n"
    "You'll be running for your lives\n"
    "When the fire's in the sky\n"
    "Prepare yourselves to die\n\n"
    "When the fire's in the sky\n"
    "You'll be running for your lives\n"
    "When the fire's in the sky\n"
    "Prepare yourselves to die\n"
    "To die, to die, to die, to die\n",

        //The Trooper

    "You'll take my life, but I'll take yours too\n"
    "You'll fire your musket, but I'll run you through\n"
    "So when you're waiting for the next attack\n"
    "You'd better stand, there's no turning back\n\n"
    "The bugle sounds, the charge begins\n"
    "But on this battlefield, no one wins\n"
    "The smell of acrid smoke and horses' breath\n"
    "As I plunge on into certain death, oh, oh\n\n"
    "The horse, he sweats with fear, we break to run\n"
    "The mighty roar of the Russian guns\n"
    "And as we race towards the human wall\n"
    "The screams of pain as my comrades fall\n\n"
    "We hurdle bodies that lay on the ground\n"
    "And the Russians fire another round\n"
    "We get so near, yet so far away\n"
    "We were meant to fight another day, oh, oh\n\n"
    "We get so close, near enough to fight\n"
    "When a Russian gets me in his sights\n"
    "He pulls the trigger and I feel the blow\n"
    "A burst of rounds take my horse below\n\n"
    "And as I lay there gazing at the sky\n"
    "My body's numb and my throat is dry\n"
    "And as I lay forgotten and alone\n"
    "Without a tear, I draw my parting groan, oh, oh\n",


                //Prisoner of Your (Hazel) Eyes

    "When I saw your face\n"
    "I became a prisoner of your eyes\n"
    "And I would do just anything\n"
    "To stay and be with you\n\n"
    "You know there are times\n"
    "When I let myself wonder\n"
    "As I was going under\n"
    "You pulled me back to earth\n\n"
    "Don't you hear me crying?\n"
    "Take me in your arms again\n"
    "Tell me that you're trying\n"
    "Or is our love a lie?\n\n"
    "Love is blind\n"
    "And love deceives you\n"
    "You came along and captured me\n"
    "Now I'm a prisoner of your eyes\n"
    "Trapped in time\n"
    "I cannot leave you\n"
    "I'm just a prisoner of your eyes\n\n"
    "As each day goes by\n"
    "I've given up completely\n"
    "I've locked myself inside your heart\n"
    "And thrown away the key\n\n"
    "Only time will tell\n"
    "If I can live without you\n"
    "Can you see into the future?\n"
    "Will you ever set me free?\n\n"
    "Don't you hear me crying?\n"
    "Take me in your arms again\n"
    "Tell me that you're trying\n"
    "Or is our love a lie?\n\n"
    "Love is blind\n"
    "And love deceives you\n"
    "You came along and captured me\n"
    "Now I'm a prisoner of your eyes\n"
    "Trapped in time\n"
    "I cannot leave you\n"
    "I'm just a prisoner of your eyes\n\n"
    "In this heartache\n"
    "We can try and start again\n"
    "Stop the heartbreak\n"
    "A little time will help to kill the pain\n\n"
    "Don't you hear me crying?\n"
    "Take me in your arms again\n"
    "Tell me that you're trying\n"
    "Or is our love a lie?\n\n"
    "Love is blind\n"
    "And love deceives you\n"
    "You came along and captured me\n"
    "Now I'm a prisoner of your eyes\n"
    "Trapped in time\n"
    "I cannot leave you\n"
    "I'm just a prisoner of your eyes\n\n"
    "Love is blind\n"
    "And love deceives you\n"
    "You came along and captured me\n"
    "Now I'm a prisoner of your eyes\n"
    "Trapped in time\n"
    "I cannot leave you\n"
    "I'm just a prisoner of your eyes\n\n"
    "Love is blind\n"
    "And love deceives you\n"
    "You came along and captured me\n"
    "Now I'm a prisoner of your eyes\n"
    "Trapped in time\n"
    "I cannot leave you\n"
    "I'm just a prisoner of your eyes\n"






    
};

char *WhiteGirlPop[] = { 
    
    //1 - Britney Spears - Toxic
    "Baby, can't you see I'm callin'?\n"
    "A guy like you should wear a warnin'\n"
    "It's dangerous, I'm fallin'\n"
    "There's no escape, I can't wait\n"
    "I need a hit, baby, give me it\n"
    "You're dangerous, I'm lovin' it\n"
    "Too high, can't come down\n"
    "Losing my head, spinnin' 'round and 'round\n"
    "Do you feel me now?\n"
    "With a taste of your lips, I'm on a ride\n"
    "You're toxic, I'm slippin' under\n"
    "With a taste of a poison paradise\n"
    "I'm addicted to you\n"
    "Don't you know that you're toxic?\n"
    "And I love what you do\n"
    "Don't you know that you're toxic?\n"
    "It's gettin' late to give you up\n"
    "I took a sip from my devil's cup\n"
    "Slowly, it's takin' over me\n"
    "Too high, can't come down\n"
    "It's in the air and it's all around\n"
    "Can you feel me now?\n"
    "With a taste of your lips, I'm on a ride\n"
    "You're toxic, I'm slippin' under\n"
    "With a taste of a poison paradise\n"
    "I'm addicted to you\n"
    "Don't you know that you're toxic?\n"
    "And I love what you do\n"
    "Don't you know that you're toxic?\n"
    "Don't you know that you're toxic?\n"
    "Taste of your lips, I'm on a ride\n"
    "You're toxic, I'm slippin' under\n"
    "With a taste of a poison paradise\n"
    "I'm addicted to you\n"
    "Don't you know that you're toxic?\n"
    "With a taste of your lips, I'm on a ride\n"
    "You're toxic, I'm slippin' under (Toxic)\n"
    "With a taste of a poison paradise\n"
    "I'm addicted to you\n"
    "Don't you know that you're toxic?\n"
    "Intoxicate me now with your lovin' now\n"
    "I think I'm ready now (I think I'm ready now)\n"
    "Intoxicate me now with your lovin' now\n"
    "I think I'm ready now\n",

    //2 - Britney Spears - Gimme More
    "It's Britney, bitch\n"
    "I see you\n"
    "And I just wanna dance with you\n"
    "Every time they turn the lights down\n"
    "Just wanna go that extra mile for you\n"
    "Public display of affection (Oh-oh-oh)\n"
    "Feels like no one else in the room (But you)\n"
    "We can get down\n"
    "Like there's no one around\n"
    "We keep on rocking (We keep on rocking)\n"
    "We keep on rocking (We keep on rocking)\n"
    "Cameras are flashing\n"
    "While we're dirty dancing\n"
    "They keep watching (They keep watching)\n"
    "Keep watching, feels like the crowd is saying\n"
    "Gimme, gimme (More), gimme (More)\n"
    "Gimme, gimme (More)\n"
    "Gimme, gimme (More), gimme (Mo')\n"
    "Gimme, gimme (More)\n"
    "Gimme, gimme (More), gimme (More)\n"
    "Gimme, gimme (More)\n"
    "Gimme, gimme (More), gimme (Mo')\n"
    "Gimme, gimme (More)\n"
    "The center of attention (Do you feel that?)\n"
    "Even when we're up against the wall\n"
    "You got me in a crazy position (Yeah)\n"
    "If you're on a mission (Uh-huh), you got my permission (Oh)\n"
    "We can get down\n"
    "Like there's no one around\n"
    "We keep on rocking (Keep on rocking)\n"
    "We keep on rocking (Oh), rocking (Uh-huh)\n"
    "Cameras are flashing\n"
    "While we're dirty dancing\n"
    "They keep watching (They keep watching)\n"
    "Keep watching, feels like the crowd is saying\n"
    "Gimme, gimme (More), gimme (More)\n"
    "Gimme, gimme (More)\n"
    "Gimme, gimme (More), gimme (Mo')\n"
    "Gimme, gimme (More)\n"
    "Gimme, gimme (More), gimme (More)\n"
    "Gimme, gimme (More)\n"
    "Gimme, gimme (More), gimme (Mo')\n"
    "Gimme, gimme (More)\n"
    "Ooh-ooh-ooh\n"
    "Ooh-ooh-ooh (I just can't)\n"
    "Ooh-ooh-ooh (Control myself)\n"
    "Ooh-ooh-ooh (More)\n"
    "Ooh-ooh-ooh (They want more?)\n"
    "Ooh-ooh-ooh\n"
    "Ooh-ooh-ooh (Well, I'll give them more)\n"
    "Ooh-ooh-ooh (Ow, more)\n"
    "Gimme, gimme (More), gimme (More)\n"
    "Gimme, gimme (More), give me more\n"
    "Gimme, gimme (More), gimme (Mo')\n"
    "Gimme, gimme (More), ooh-ooh\n"
    "Gimme, gimme (More), gimme (More)\n"
    "Gimme, gimme (More)\n"
    "Gimme, gimme (More), give me more, gimme (Mo'), yeah\n"
    "Gimme, gimme (More)\n"
    "Oh-oh-oh\n"
    "Gimme more, gimme more\n"
    "Mo— Mo— Mo— Mo— Mo— Mo— Mo— (More)\n"
    "Gimme more, gimme more, babe\n"
    "Danja, Danja, Danja, Danja\n"
    "Danja, Danja, Danja, Danja (I just want more)\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Ooh-oh, ah-ah-ah, ah\n"
    "Gimme, gimme, gimme\n"
    "Gimme, gimme\n"
    "Gimme, gimme, gimme\n"
    "(Danja, Danja, Danja, Danja)\n"
    "Gimme, gimme (Danja, Danja, Danja, Danja)\n"
    "Gimme, gimme, gimme\n"
    "Gimme, gimme\n"
    "Gimme, gimme, gimme\n"
    "Gimme, gimme\n"
    "Bet you didn't see this one coming\n"
    "The Incredible Lago (Mo— Mo— Mo— Mo— Mo— Mo— Mo—)\n"
    "The legendary Miss Britney Spears, haha\n"
    "And the unstoppable Danja\n"
    "Ah, you gonna have to remove me\n"
    "'Cause I ain't going nowhere\n"
    "Mo— Mo— Mo— Mo— Mo— Mo— Mo— (More)\n",

    //3 - Britney Spears - Oops!...I Did It Again
    "Mmm, yeah\n"
    "Yeah, yeah, yeah, yeah, yeah, yeah\n"
    "Yeah, yeah, yeah, yeah, yeah, yeah\n"
    "I think I did it again\n"
    "I made you believe we're more than just friends\n"
    "Oh, baby, it might seem like a crush\n"
    "But it doesn't mean that I'm serious\n"
    "'Cause to lose all my senses\n"
    "That is just so typically me\n"
    "Ooh, baby, baby\n"
    "Oops, I did it again,\n"
    "I played with your heart\n"
    "Got lost in the game\n"
    ", oh, baby, baby\n"
    "Oops, you think I'm in love, that I'm sent from above\n"
    "I'm not that innocent\n"
    "You see, my problem is this\n"
    "I'm dreamin' away\n"
    "Wishin' that heroes, they truly exist\n"
    "I cry watching the days\n"
    "Can't you see I'm a fool in so many ways?\n"
    "But to lose all my senses\n"
    "That is just so typically me\n"
    "Oh, baby, oh\n"
    "Oops, I did it again, I played with your heart\n"
    "Got lost in the game, oh, baby, baby\n"
    "Oops, you think I'm in love, that I'm sent from above\n"
    "I'm not that innocent\n"
    "Yeah, yeah, yeah, yeah, yeah, yeah\n"
    "Yeah, yeah, yeah, yeah, yeah, yeah\n"
    "\"All aboard!\"\n"
    "\"Britney! Before you go, there's something I want you to have.\"\n"
    "\"Oh, it's beautiful! But wait a minute, isn't this...?\"\n"
    "\"Yeah, yes, it is.\"\n"
    "\"But I thought the old lady dropped it into the ocean in the end.\"\n"
    "\"Well, baby, I went down and got it for ya.\"\n"
    "\"Aw, you shouldn't have\"\n"
    "Oops, I did it again to your heart\n"
    "Got lost in this game, oh, baby (Baby)\n"
    "Oops, you (Oops, you), think that I'm sent from above\n"
    "I'm not that innocent\n"
    "Oops, I did it again, I played with your heart\n"
    "Got lost in the game (Yeah, yeah), oh, baby, baby\n"
    "Oops, you think I'm in love, that I'm sent from above (Yeah, yeah)\n"
    "I'm not that innocent (Not that innocent, babe)\n"
    "Oops, I (Oops, I) did it again (Did it again to your heart), I played with your heart (Got lost)\n"
    "Got lost in the game (In this game, oh, baby), oh, baby, baby\n"
    "Oops, you (Oops, you) think I'm in love (Think that I'm sent), that I'm sent from above\n"
    "I'm not that innocent\n",

    //4 - Rihanna - S&M
    "Na-na-na, come on\n"
    "Na-na-na, come on\n"
    "Na-na-na-na-na, come on\n"
    "Na-na-na, come on, come on, come on\n"
    "Na-na-na-na, come on\n"
    "Na-na-na, come on\n"
    "Na-na-na-na-na, come on\n"
    "Na-na-na, come on, come on, come on\n"
    "Na-na-na-na\n"
    "Feels so good being bad (Oh-oh-oh-oh-oh)\n"
    "There's no way I'm turning back (Oh-oh-oh-oh-oh)\n"
    "Now the pain is my pleasure 'cause nothing could measure\n"
    "(Oh, oh, oh-oh-oh-oh-oh)\n"
    "Love is great, love is fine (Oh-oh-oh-oh-oh)\n"
    "Out the box, outta line (Oh-oh-oh-oh-oh)\n"
    "The affliction of the feeling leaves me wanting more\n"
    "(Oh, oh, oh-oh-oh-oh-oh)\n"
    "'Cause I may be bad, but I'm perfectly good at it\n"
    "Sex in the air, I don't care, I love the smell of it\n"
    "Sticks and stones may break my bones\n"
    "But chains and whips excite me\n"
    "'Cause I may be bad, but I'm perfectly good at it\n"
    "Sex in the air, I don't care, I love the smell of it\n"
    "Sticks and stones may break my bones\n"
    "But chains and whips excite me\n"
    "Na-na-na, come on, come on, come on\n"
    "I like it, like it\n"
    "Come on, come on, come on\n"
    "I like it, like it (Na-na-na)\n"
    "Come on, come on, come on\n"
    "I like it, like it\n"
    "Come on, come on, come on\n"
    "I like it, like it\n"
    "Love is great, love is fine (Oh-oh-oh-oh-oh)\n"
    "Out the box, outta line (Oh-oh-oh-oh-oh)\n"
    "The affliction of the feeling leaves me wanting more\n"
    "(Oh, oh, oh-oh-oh-oh-oh)\n"
    "'Cause I may be bad, but I'm perfectly good at it\n"
    "Sex in the air, I don't care, I love the smell of it\n"
    "Sticks and stones may break my bones\n"
    "But chains and whips excite me\n"
    "Na-na-na, come on, come on, come on\n"
    "I like it, like it\n"
    "Come on, come on, come on\n"
    "I like it, like it (Na-na-na)\n"
    "Come on, come on, come on\n"
    "I like it, like it\n"
    "Come on, come on, come on\n"
    "I like it, like it\n"
    "S-S-S and M-M-M\n"
    "S-S-S and M-M-M\n"
    "Oh, I love the feeling you bring to me\n"
    "Oh, you turn me on\n"
    "It's exactly what I've been yearning for\n"
    "Give it to me strong\n"
    "And meet me in my boudoir\n"
    "Make my body say, \"Ah-ah-ah\"\n"
    "I like it, like it\n"
    "'Cause I may be bad, but I'm perfectly good at it\n"
    "Sex in the air, I don't care, I love the smell of it\n"
    "Sticks and stones may break my bones\n"
    "But chains and whips excite me\n"
    "'Cause I may be bad, but I'm perfectly good at it\n"
    "Sex in the air, I don't care, I love the smell of it\n"
    "Sticks and stones may break my bones\n"
    "But chains and whips excite me\n"
    "Na-na-na, come on, come on, come on\n"
    "I like it, like it\n"
    "Come on, come on, come on\n"
    "I like it, like it (Na-na-na)\n"
    "Come on, come on, come on\n"
    "I like it, like it\n"
    "Come on, come on, come on\n"
    "I like it, like it\n"
    "S-S-S and M-M-M\n"
    "S-S-S and M-M-M\n"
    "S-S-S and M-M-M\n"
    "S-S-S and M-M-M\n",

    //5 - Carly Rae Jepsen - Call Me Maybe
    "I threw a wish in the well\n"
    "Don't ask me, I'll never tell\n"
    "I looked to you as it fell\n"
    "And now you're in my way\n"
    "I trade my soul for a wish\n"
    "Pennies and dimes for a kiss\n"
    "I wasn't lookin' for this\n"
    "But now you're in my way\n"
    "Your stare was holdin'\n"
    "Ripped jeans, skin was showin'\n"
    "Hot night, wind was blowin'\n"
    "Where you think you're goin', baby?\n"
    "Hey, I just met you, and this is crazy\n"
    "But here's my number, so call me maybe\n"
    "It's hard to look right at you, baby\n"
    "But here's my number, so call me maybe\n"
    "Hey, I just met you, and this is crazy\n"
    "But here's my number, so call me maybe\n"
    "And all the other boys try to chase me\n"
    "But here's my number, so call me maybe\n"
    "You took your time with the call\n"
    "I took no time with the fall\n"
    "You gave me nothin' at all\n"
    "But still, you're in my way\n"
    "I beg and borrow and steal\n"
    "At first sight, and it's real\n"
    "I didn't know I would feel it\n"
    "But it's in my way\n"
    "Your stare was holdin'\n"
    "Ripped jeans, skin was showin'\n"
    "Hot night, wind was blowin'\n"
    "Where you think you're goin', baby?\n"
    "Hey, I just met you, and this is crazy\n"
    "But here's my number, so call me maybe\n"
    "It's hard to look right at you, baby\n"
    "But here's my number, so call me maybe\n"
    "Hey, I just met you, and this is crazy\n"
    "But here's my number, so call me maybe\n"
    "And all the other boys try to chase me\n"
    "But here's my number, so call me maybe\n"
    "Before you came into my life, I missed you so bad\n"
    "I missed you so bad, I missed you so, so bad\n"
    "Before you came into my life, I missed you so bad\n"
    "And you should know that, I missed you so, so bad\n"
    "It's hard to look right at you, baby\n"
    "But here's my number, so call me maybe\n"
    "Hey, I just met you, and this is crazy\n"
    "But here's my number, so call me maybe\n"
    "It's hard to look right at you, baby\n"
    "But here's my number, so call me maybe\n"
    "Hey, I just met you, and this is crazy\n"
    "But here's my number, so call me maybe\n"
    "And all the other boys try to chase me\n"
    "But here's my number, so call me maybe\n"
    "Hey, I just met you, and this is crazy\n"
    "But here's my number, so call me maybe\n"
    "And all the other boys try to chase me\n"
    "But here's my number, so call me maybe\n"
    "Before you came into my life, I missed you so bad\n"
    "I missed you so bad, I missed you so, so bad\n"
    "Before you came into my life, I missed you so bad\n"
    "And you should know that\n",

    //6 - Lady Gaga - Bad Romance
    "Oh, caught in a bad romance\n"
    "Oh, caught in a bad romance\n"
    "Ra, ra, ah-ah-ah\n"
    "Roma, roma-ma\n"
    "Gaga, ooh, la, la\n"
    "Want your bad romance\n"
    "Ra, ra, ah-ah-ah\n"
    "Roma, roma-ma\n"
    "Gaga, ooh, la, la\n"
    "Want your bad romance\n"
    "I want your ugly, I want your disease\n"
    "I want your everything as long as it's free\n"
    "I want your love\n"
    "Love, love, love, I want your love, ayy\n"
    "I want your drama, the touch of your hand ( Hey )\n"
    "I want your leather-studded kiss in the sand\n"
    "I want your love\n"
    "Love, love, love, I want your love\n"
    "(Love, love, love, I want your love)\n"
    "You know that I want you\n"
    "And you know that I need you\n"
    "I want it bad, your bad romance\n"
    "I want your love and I want your revenge\n"
    "You and me could write a bad romance (Oh)\n"
    "I want your love and all your lover's revenge\n"
    "You and me could write a bad romance\n"
    "Oh, caught in a bad romance\n"
    "Oh, caught in a bad romance\n"
    "Ra, ra, ah-ah-ah\n"
    "Roma, roma-ma\n"
    "Gaga, ooh, la, la\n"
    "Want your bad romance\n"
    "I want your horror, I want your design\n"
    "'Cause you're a criminal as long as you're mine\n"
    "I want your love\n"
    "Love, love, love, I want your love\n"
    "I want your psycho, your vertigo schtick (Hey)\n"
    "Want you in my rear window, baby, you're sick\n"
    "I want your love\n"
    "Love, love, love, I want your love\n"
    "(Love, love, love, I want your love)\n"
    "You know that I want you\n"
    "And you know that I need you ('Cause I'm a free bitch, baby)\n"
    "I want it bad, your bad romance\n"
    "I want your love and I want your revenge\n"
    "You and me could write a bad romance (Oh)\n"
    "I want your love and all your lover's revenge\n"
    "You and me could write a bad romance\n"
    "Oh, caught in a bad romance\n"
    "Oh, caught in a bad romance\n"
    "Ra, ra, ah-ah-ah\n"
    "Roma, roma-ma\n"
    "Gaga, ooh, la, la\n"
    "Want your bad romance\n"
    "Ra, ra, ah-ah-ah\n"
    "Roma, roma-ma\n"
    "Gaga, ooh, la, la\n"
    "Want your bad romance\n"
    "Walk, walk, fashion, baby\n"
    "Work it, move that bitch crazy\n"
    "Walk, walk, fashion, baby\n"
    "Work it, move that bitch crazy\n"
    "Walk, walk, fashion, baby\n"
    "Work it, move that bitch crazy\n"
    "Walk, walk, passion, baby\n"
    "Work it, I'm a free bitch, baby\n"
    "I want your love and I want your revenge\n"
    "I want your love, I don't wanna be friends\n"
    "Je veux ton amour et je veux ta revanche\n"
    "Je veux ton amour, I don't wanna be friends (Oh)\n"
    "(I want your bad romance, I want your bad romance)\n"
    "No, I don't wanna be friends (Caught in a bad romance)\n"
    "(I want your bad romance, I want your bad romance)\n"
    "I don't wanna be friends (Oh)\n"
    "(I want your bad romance, I want your bad romance)\n"
    "Want your bad romance (I want your bad romance)\n"
    "Caught in a bad romance\n"
    "Want your bad romance\n"
    "I want your love and I want your revenge\n"
    "You and me could write a bad romance (Oh)\n"
    "I want your love and all your lover's revenge\n"
    "You and me could write a bad romance\n"
    "Oh (Want your bad romance)\n"
    "Caught in a bad romance (Want your bad romance)\n"
    "Oh (Want your bad romance)\n"
    "Caught in a bad romance\n"
    "Ra, ra, ah-ah-ah\n"
    "Roma, roma-ma\n"
    "Gaga, ooh, la, la\n"
    "Want your bad romance\n",

    //7 - Lady Gaga - Judas
    "Woah-woah-woah-woah-woah\n"
    "I'm in love with Juda-as, Juda-as\n"
    "Woah-woah-woah-woah-woah\n"
    "I'm in love with Juda-as, Juda-as\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Gaga\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Gaga\n"
    "When he calls to me, I am ready\n"
    "I'll wash his feet with my hair if he needs\n"
    "Forgive him when his tongue lies through his brain\n"
    "Even after three times, he betrays me\n"
    "(Ah-ah, ah-ah, ah-ah, ah-ah)\n"
    "I'll bring him down, bring him down, down\n"
    "(Ah-ah, ah-ah, ah-ah, ah-ah)\n"
    "A king with no crown, king with no crown\n"
    "I'm just a Holy Fool, oh, baby, it's so cruel\n"
    "But I'm still in love with Judas, baby\n"
    "I'm just a Holy Fool, oh, baby, it's so cruel\n"
    "But I'm still in love with Judas, baby\n"
    "Woah-woah-woah-woah-woah\n"
    "I'm in love with Juda-as, Juda-as\n"
    "Woah-woah-woah-woah-woah\n"
    "I'm in love with Juda-as, Juda-as\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Gaga\n"
    "I couldn't love a man so purely\n"
    "Even prophets forgave his goofy way\n"
    "I've learned love is like a brick, you can\n"
    "Build a house or sink a dead body\n"
    "(Ah-ah, ah-ah, ah-ah, ah-ah)\n"
    "I'll bring him down, bring him down, down\n"
    "(Ah-ah, ah-ah, ah-ah, ah-ah)\n"
    "A king with no crown, king with no crown\n"
    "I'm just a Holy Fool, oh, baby, it's so cruel\n"
    "But I'm still in love with Judas, baby\n"
    "I'm just a Holy Fool, oh, baby, it's so cruel\n"
    "But I'm still in love with Judas, baby\n"
    "Woah-woah-woah-woah-woah\n"
    "I'm in love with Juda-as, Juda-as\n"
    "Woah-woah-woah-woah-woah\n"
    "I'm in love with Juda-as, Juda-as\n"
    "*Ew*\n"
    "In the most Biblical sense (Ew)\n"
    "I am beyond repentance\n"
    "Fame, hooker, prostitute, wench\n"
    "Vomits her mind\n"
    "But in the cultural sense\n"
    "I just speak in future tense\n"
    "Judas, kiss me, if offenced\n"
    "Or wear ear condom next time\n"
    "I wanna love you\n"
    "But something's pulling me away from you\n"
    "Jesus is my virtue\n"
    "And Judas is the demon I cling to\n"
    "I cling to\n"
    "Just a Holy Fool, oh, baby, it's so cruel\n"
    "But I'm still in love with Judas, baby\n"
    "I'm just a Holy Fool, oh, baby, it's so cruel (Just a Holy Fool, woah-oh-oh)\n"
    "But I'm still in love with Judas, baby\n"
    "Woah-woah-woah-woah-woah (Woah)\n"
    "I'm in love with Juda-as, Juda-as (Juda-a-as)\n"
    "Woah-woah-woah-woah-woah (Woah)\n"
    "I'm in love with Juda-as, Juda-as (Juda-a-as)\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Juda-ah-ah\n"
    "Judas, Gaga\n",

    //8 - Britney Spears - If U Seek Amy (fuck me lol...don't take the parens serious I am joking here but title spells that doesn't it F u c k me)
    "La, la, la, la, la-la, la, la\n"
    "La, la, la, la, la-la, la, la\n"
    "La, la, la, la, la-la, la, la\n"
    "La, la, la, la, la-la, la, la\n"
    "Oh, baby, baby, have you seen Amy tonight?\n"
    "Is she in the bathroom? Is she smoking up outside? ( Oh )\n"
    "Oh, baby, baby, does she take a piece of lime\n"
    "For the drink that I'ma buy her? Do you know just what she likes? (Oh)\n"
    "Oh, oh, tell me, have you seen her?\n"
    "'Cause I'm so, oh, I can't get her off of my brain\n"
    "I just wanna go to the party she gon' go\n"
    "Can somebody take me home? Ha-ha, hee-hee, ha-ha, ho\n"
    "Love me, hate me, say what you want about me\n"
    "But all of the boys and all of the girls are begging to, if you seek Amy\n"
    "Love me, hate me, but can't you see what I see?\n"
    "All of the boys and all of the girls are begging to, if you seek Amy\n"
    "( Love me, hate me )\n"
    "La, la, la, la, la-la, la, la\n"
    "La, la, la, la, la-la, la, la\n"
    "Amy told me that she's gonna meet me up\n"
    "I don't know where or when, and now they're closing up the club ( Oh )\n"
    "I've seen her once or twice before, she knows my face\n"
    "But it's hard to see with all the people standing in the way ( Oh )\n"
    "Oh, oh, tell me, have you seen her?\n"
    "'Cause I'm so, oh, I can't get her off of my brain\n"
    "I just wanna go to the party she gon' go\n"
    "Can somebody take me home? Ha-ha, hee-hee, ha-ha, ho\n"
    "Love me, hate me, say what you want about me\n"
    "But all of the boys and all of the girls are begging to, if you seek Amy\n"
    "Love me, hate me, but can't you see what I see?\n"
    "All of the boys and all of the girls are begging to, if you seek Amy\n"
    "(Love me, hate me) Oh, say what you want about me\n"
    "Oh, but can't you see what I see?\n"
    "(Love me, hate me) Yeah, say what you want about me\n"
    "So tell me if you see her\n"
    "( Let me know what she was wearing and what she was like )\n"
    "'Cause I've been waiting here forever\n"
    "( Let me know if she was going out her mind )\n"
    "Oh, baby, baby, if you seek Amy tonight ( Oh )\n"
    "Oh, baby, baby, we'll do whatever you like\n"
    "Oh, baby, baby, baby\n"
    "Oh, baby, baby, baby\n"
    "La, la, la, la, la-la, la, la\n"
    "La, la, la, la, la-la, la, la\n"
    "La, la, la, la, la-la, la, la\n"
    "La, la, la, la, la-la, la, la\n"
    "Love me, hate me, say what you want about me\n"
    "But all of the boys and all of the girls are begging to, if you seek Amy\n"
    "Love me, hate me, but can't you see what I see?\n"
    "All of the boys and all of the girls are begging to, if you seek Amy\n"
    "Love me, hate me, say what you want about me (Yeah, yeah)\n"
    "Love me, hate me, but can't you see what I see?\n"
    "All of the boys and all of the girls are begging to, if you seek Amy\n"
    "(Love me, hate me) Oh, say what you want about me\n"
    "Oh, but can't you see what I see?\n"
    "(Love me, hate me) Yeah, say what you want about me\n"
    "All of the boys and all of the girls are begging to, if you seek Amy\n",

    //9 - Katy Perry - I Kissed a Girl
    "This was never the way I planned\n"
    "Not my intention\n"
    "I got so brave, drink in hand\n"
    "Lost my discretion\n"
    "It's not what I'm used to\n"
    "Just wanna try you on\n"
    "I'm curious for you\n"
    "Caught my attention\n"
    "I kissed a girl and I liked it\n"
    "The taste of her cherry ChapStick\n"
    "I kissed a girl just to try it\n"
    "I hope my boyfriend don't mind it\n"
    "It felt so wrong, it felt so right\n"
    "Don't mean I'm in love tonight\n"
    "I kissed a girl and I liked it\n"
    "I liked it\n"
    "No, I don't even know your name\n"
    "It doesn't matter\n"
    "You're my experimental game\n"
    "Just human nature\n"
    "It's not what good girls do\n"
    "Not how they should behave\n"
    "My head gets so confused\n"
    "Hard to obey\n"
    "I kissed a girl and I liked it\n"
    "The taste of her cherry ChapStick\n"
    "I kissed a girl just to try it\n"
    "I hope my boyfriend don't mind it\n"
    "It felt so wrong, it felt so right\n"
    "Don't mean I'm in love tonight\n"
    "I kissed a girl and I liked it\n"
    "I liked it\n"
    "Us girls, we are so magical\n"
    "Soft skin, red lips, so kissable\n"
    "Hard to resist, so touchable\n"
    "Too good to deny it\n"
    "Ain't no big deal, it's innocent\n"
    "I kissed a girl and I liked it\n"
    "The taste of her cherry ChapStick\n"
    "I kissed a girl just to try it\n"
    "I hope my boyfriend don't mind it\n"
    "It felt so wrong, it felt so right\n"
    "Don't mean I'm in love tonight\n"
    "I kissed a girl and I liked it\n"
    "I liked it\n",

        //10 - ...Baby One More Time - Britney Spears
    "Oh, baby, baby\n"
    "Oh, baby, baby\n\n"
    "Oh, baby, baby\n"
    "How was I supposed to know\n"
    "That somethin' wasn't right here?\n"
    "Oh, baby, baby\n"
    "I shouldn't have let you go\n"
    "And now you're out of sight, yeah\n\n"
    "Show me how you want it to be\n"
    "Tell me, baby, 'cause I need to know now\n"
    "Oh, because\n\n"
    "My loneliness is killin' me (And I)\n"
    "I must confess, I still believe (Still believe)\n"
    "When I'm not with you, I lose my mind\n"
    "Give me a sign\n"
    "Hit me, baby, one more time\n\n"
    "Oh, baby, baby\n"
    "The reason I breathe is you (Oh yeah)\n"
    "Boy, you got me blinded\n"
    "Oh, pretty baby\n"
    "There's nothing that I wouldn't do\n"
    "It's not the way I planned it\n\n"
    "Show me how you want it to be\n"
    "Tell me, baby, 'cause I need to know now\n"
    "Oh, because\n\n"
    "My loneliness is killin' me (And I)\n"
    "I must confess, I still believe (Still believe)\n"
    "When I'm not with you, I lose my mind\n"
    "Give me a sign\n"
    "Hit me, baby, one more time\n\n"
    "Oh, baby, baby (Oh)\n"
    "Oh, baby, baby (Yeah, yeah)\n\n"
    "Oh, baby, baby\n"
    "How was I supposed to know?\n"
    "Oh, pretty baby\n"
    "I shouldn't have let you go\n"
    "I must confess that my loneliness is killin' me now\n"
    "Don't you know I still believe\n"
    "That you will be here and give me a sign?\n"
    "Hit me, baby, one more time\n\n"
    "My loneliness is killin' me (And I)\n"
    "I must confess, I still believe (Still believe)\n"
    "When I'm not with you, I lose my mind\n"
    "Give me a sign\n"
    "Hit me, baby, one more time\n\n"
    "I must confess that my loneliness (My loneliness is killin' me)\n"
    "Is killin' me now (I must confess, I still believe)\n"
    "Don't you know I still believe (When I'm not with you, I lose my mind)\n"
    "That you will be here and give me a sign?\n"
    "Hit me, baby, one more time\n",

};
char *depressed_titles[] = {
    "Bring Me To Life - Evanescence",
    "Lithium - Evanescence",
    "My Immortal - Evanescence",
    "I Hate Everything About You - Three Days Grace",
    "Pain - Three Days Grace",
    "Boulevard of Broken Dreams - Green Day",
    "Unforgiven - Metallica",
    "Fade To Black - Metallica",
    "How You Remind Me - Nickelback",
    "Lithium - Nirvana",
    "Still Loving You - Scorpions",
    NULL
};


char *nightcoreTitles[] = {        
    "Angel with a Shotgun",
    "Rockefeller Street",
    "Teeth",
    "Thunder",
    "Take a Hint",
    "How to be a Heartbreaker",
    "Light it Up",
    "Pretty Rave Girl",
    "All I Ever Wanted",
    "Angel Of Darkness",
    "Pretty Little Psycho",
    NULL
};


char *nwobhmTitles[] = {
    "Ace of Spades - Motörhead", 
    "Overkill - Motörhead",
     "Too Late Too Late - Motörhead",
    "Am I Evil - Diamondhead",
    "In The Heat of The Night - Diamondhead",
    "Denim&Leather - Saxon",
    "Crusader - Saxon",
    "Fire In The Sky - Saxon",
    "The Trooper - Iron Maiden",
    "Prisoner Of Your Eyes - Judas Priest", 
    NULL
}; //Note to future self...Don't forget NULL or you'll get core dump (like how she dumped you...but bright side:You found the bug under a min since you are used to get dumped)

char *WhiteGirlPopTitles[] = {
    "Toxic - Britney Spears",
    "Gimme More - Britney Spears",
    "Oops I Did It Again - Britney Spears",
    "S&M - Rihanna",
    "Call Me Maybe - Carly Rae Jepsen",
    "Bad Romance - Lady Gaga",
    "Judas - Lady Gaga",
    "If U Seek Amy - Britney Spears",
    "I Kissed A Girl - Kety Parry", //I sure did lol
    "...Baby One More Time - Britney Spears",
    NULL
};


char *myTherapySessionAudio[] = {
    "https://drive.google.com/uc?export=open&id=1vzC0YESu0JxHRP6hxKO1TS54FOXHw3c5", //Bring Me To Life
    "https://drive.google.com/uc?export=open&id=1Ea99sesm8Ho-gp08jaySqgwXB_-MR-oj", // Lithium Eva
    "https://drive.google.com/uc?export=open&id=1_bPQGDr58Sk_gZLP_FgB-0O7RMi5f6sE",//My immortal
    "https://drive.google.com/uc?export=open&id=19XGnFxFeJG68XmTbckq5_BpfkIK5udey",//I (wanna) hate everything about you 
    "https://drive.google.com/uc?export=open&id=1YdCiss7e9pFfuuhDxpAB91kjxflPOdw5",//Pain 
    "https://drive.google.com/uc?export=open&id=1XHR_qNuP2VCISxJrhnzFqrNKhS8XpfeN",//Broken Dreams
    "https://drive.google.com/uc?export=open&id=18G2SYGLKntyhzgLXZJ0LJdmkNkxpJf5E", //Unforgiven
    "https://drive.google.com/uc?export=open&id=1CpFLSZwQliL9uDfYplewixTY4iuvlid4",//Fade To Black
    "https://drive.google.com/uc?export=open&id=1fPDH35PpZqSxNUxW0Pxrakv5iSvKi8u1", //How you remind me
    "https://drive.google.com/uc?export=open&id=1C-IcedC0m2aRJnGNpLztS-960AE4QIP4", //Lithium -Nirvana
    "https://drive.google.com/uc?export=open&id=10XGgVvBJJkP6XLux0OhKcqzENPZ07nF0"
};

char *ADHDSongsAudio[] = {
    
    "https://drive.google.com/uc?export=open&id=1QmFON5P2dDa0_0-Qwn_l6iPlNsdhyYQc", //Angel with a shotgun
    "https://drive.google.com/uc?export=open&id=1mFC4ZYCDnyHU7kAkYi_ujsKwZGU_imBN",  //Rockefeller street
    "https://drive.google.com/uc?export=open&id=1OW6MmzzRFk-fN7ztpcm-Zwm3LnB8KYJO", //Teeth
    "https://drive.google.com/uc?export=open&id=1myR3WUpP7mtgBK62_6vFB7zmk-wbt5bP", //Thunder
    "https://drive.google.com/uc?export=open&id=1uU2mjKzS-wUUxcwGJ4Dsv2tDOx0zfWeE", //Take a Hint
    "https://drive.google.com/uc?export=open&id=1AcytXQetZIAHnfpg7parij8JTmKTSKiT", //How to be a Heartbreak
    "https://drive.google.com/uc?export=open&id=165F_05Gmr-iz5gjTTAjcwaEB9pZpHWLz", //Light it UP MF
    "https://drive.google.com/uc?export=open&id=1mHtT9xwhyjNZKxpPsza0UgUsQTol0kZf", //The OG Nightcore pretty rave girl
    "https://drive.google.com/uc?export=open&id=1tYChoSq68A3IiyQ9A8oUe03PVOLfTAwd", //All I ever Wanted
    "https://drive.google.com/uc?export=open&id=1sU39rFpMAb4ajAFvGAsGpu3oJCv540FH", // Angel of Darkness
    "https://drive.google.com/uc?export=open&id=1AcSaE1naXCEZgP4RJVIx__Kv-Pg5D3Bf"  //Pretty Little Psycho (Me >///<)
//                                                                                                               ω 
 };

char *NWOBHMSongsAudio[] = {
    "https://drive.google.com/uc?export=open&id=1j6quK4yfQ-V4rpmDECUnWg5xglOeF22d", //Ace of Spades 
    "https://drive.google.com/uc?export=open&id=1zjgn3CeieJk7Dwn6vUkn1aWrziKY0C3N", // Overkill
    "https://drive.google.com/uc?export=open&id=1WBJrOQTFzlmkQ5z0Q_EBfvBTMcuXSK3J", // Too Late Too Late
    "https://drive.google.com/uc?export=open&id=1hEIX3vW2nalBgn2V0gyzn4iHrDjmDglz", //Am I Evil (Nope...as I said jussst autistic as fuck.)
    "https://drive.google.com/uc?export=open&id=1TA4Kpj3Oc_Cz70RUaMzlviL1uRwTf_IV", //In the heat of the night
    "https://drive.google.com/uc?export=open&id=1hrL2x7x7SRdEeJdehbuwmSik_dJBcuGR", //Denim and Leather 
    "https://drive.google.com/uc?export=open&id=10sDVNalQM0w6VEO21KmMYhmM73bnZzfP", //Crusader
    "https://drive.google.com/uc?export=open&id=1MesOIRuHZqty4OqvFhEvqjJjMuKmu6T6", //Fire in The Sky
    "https://drive.google.com/uc?export=open&id=1gKy2Juy8sBNvNUoZhSK--go2LSb1niv-", //The Trooper
    "https://drive.google.com/uc?export=open&id=1S6Ikwiyt6q5fQBJiyi8cBPpg5btZXKb2"  // Prisoner of Your (Hazel) Eyes
 };

 char *WhiteGirlPopAudio[] = {
    "https://drive.google.com/uc?export=open&id=1p1r9InaIGQYSbouOabUicTRJw2phNTfq", //Toxic (Me) 
    "https://drive.google.com/uc?export=open&id=1vICbwuedVzN-k5nt3wc5hIZECTCZyMRE", //Gimme More
    "https://drive.google.com/uc?export=open&id=1AI1qJxkp73IxiYuUrg11U07MkRYoPTQb", // Oop I Did It Again (added another genre)
    "https://drive.google.com/uc?export=open&id=1L3JPUMiqoykptsdTkF8xzRoOHouyGrbn", //S&M (suffer & modify)
    "https://drive.google.com/uc?export=open&id=1Yx_n1dMvqmZBtweq4yRkReiAy9pl7b5q", //Call Me Maybe
    "https://drive.google.com/uc?export=open&id=1XOlk2SbEp8YEQSIm0kLlmyQ59m9WJgfw", //Bad Romance 
    "https://drive.google.com/uc?export=open&id=1Jo37Lza4Z8caEuWU0mmm1GTdLY1reMye", //Judas 
    "https://drive.google.com/uc?export=open&id=1rbxz8r20K8FFt5_aDJDp6cFwu9TwuZwP", //If U Seek Amy
    "https://drive.google.com/uc?export=open&id=1o0-CpP0r-ATeY_EDvYAaehfi4--4_yii", //I Kissed A Girl
    "https://drive.google.com/uc?export=open&id=11VbU4WSPnkc-0szpSDAmLeKa96VebmK2U", //Baby one more time (one more time...one more push the greener the github heatmap the happier I am(nah I am not just a mild satisfaction it is))
 };


char *rickrollAudio = "https://drive.google.com/uc?export=open&id=10aiePDkX2t2XruCaFROIum9nGkQGUzth";
char *roast = "https://drive.google.com/uc?export=open&id=1LXCZzIJ_LR9Thw8-M2oVnKfYCHUn5obY";
char *MeaLux = "https://drive.google.com/uc?export=open&id=1oG209grBSgu_q6MxCbw-L9wMNBw5HKOe";
/*  What we do when C starts bitching? WE ADD MORE DISPATCH TABLES!!!!LESSS GO!*/


//Oh boy hard coding habits never die Now Imma fucking hard-code song lengths one by one

double myTherapySessionLengths[] = {3.54018, 3.40000, 4.03015, 3.40012, 3.24009, 3.43012, 6.10055, 4.57089, 3.33004, 4.10009, 6.43022};


double ADHDSongsLengths[] = {3.12008, 2.41013, 2.53007, 2.07002, 2.04011, 2.57005,2.01006, 2.39010, 2.25002, 2.55003,2.48000 };


double NWOBHSongsLengths[] = {2.29014, 2.45025, 2.58024, 6.5621112, 3.55024, 5.11017, 7.25131, 3.37015, 3.57037, 6.55024};

double WhiteGirlPopLengths[] = {3.32013,4.01002,3.31013,4.05001,3.19005,5.08014,4.07001,3.46006,3.04004,3.30002};


char *genres[] = {"2000s Emo Music","2000s Nightcore ADHD","New Wave of British Heavy Metal","White Girl Pop",NULL};

typedef struct {
    char *title;
    char *lyrics;
    char *url;
    int songIndex;
    int writerType; 
    double duration;
 
}songMetaData;
